### PR TITLE
Implement I2C API

### PR DESCRIPTION
**Pull request by hannobraun**
This pull request implements a basic I2C API. It currently has some limitations that are documented in the comments.

@csagonero Please take look when you get a chance and let me know what you think.

### CODE REVIEW

**Comment by hannobraun** [comment]
The CI build failed due to my formatting, so I pushed another commit to fix that. The build succeeds now, but there are a few places in the code that have become less readable as a result.

**Comment by hannobraun** [comment]
I've pushed another commit that adds a basic usage example for the MPU-9250.

**Review by pierre-rouanet — APPROVED** [review]
Hi @hannobraun,

Thanks a lot for your PR and your time! Your implementation really looks great!
Sorry you had to dig in the official documentation, but your guess about the alternate function seems good to me :)

**Comment by hannobraun** [comment]
Thanks for the review!

A small clarification:
> Sorry you had to dig in the official documentation, but your guess about the alternate function seems good to me :)

That comment you refer to applies to all the following code up to the next blank line. The alternate functions were relatively obvious, I think, but the `low_speed` and `open_drain` stuff less so. That stuff was covered nowhere in the official documentation, as far as I could tell.

**Pull request merged**
